### ISSUE TITLE
INFOGRAFIA - CICLO DE VIDA DE UN SOFTWARE

### ISSUE THREAD

**Issue by Antonia2410** [SistemasTecTlaxiaco/actividad-1-infografia-Antonia2410#1]
[CICLO DE VIDA DE UN SOFTWARE.pdf](https://github.com/user-attachments/files/16812134/CICLO.DE.VIDA.DE.UN.SOFTWARE.pdf)

**Comment by josealfredo79** [comment]
Calificacion 18, Bien hecho y revisado...
